{% set name = "cssselect2" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  skip: True    # [py<37]
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1ccd984dab89fc68955043aca4e1b03e0cf29cad9880f6e28e3ba7a74b14aa5a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - flit-core >=3.2,<4
  run:
    - python
    - tinycss2
    - webencodings

test:
  source_files:
    - tests
  imports:
    - cssselect2
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v

about:
  home: https://doc.courtbouillon.org/cssselect2/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: cssselect2 is a straightforward implementation of CSS4 Selectors for markup documents
  description: |
    cssselect2 is a straightforward implementation of CSS4 Selectors for 
    markup documents (HTML, XML, etc.) that can be read by ElementTree-like 
    parsers (including cElementTree, lxml, html5lib, etc.)
  doc_url: https://doc.courtbouillon.org/cssselect2/
  dev_url: https://github.com/Kozea/cssselect2

extra:
  recipe-maintainers:
    - johanneskoester
