travis:
  secure:
    BINSTAR_TOKEN: AjOZfWGPyFv7at/khGRsK/C1vKLtNdphnfH2HqDy3oBGANjCBOVRFgHsfW8V0ppBJ3+Uxbh44EVKZQvIpLWfcNzmhpnE19jiTjNHw2hkl+8bbTczCYE/06kLOHg7wuJFcDHN79B3zLhobxrAq77l95OXbctIUL+xTv07kr8Jr11rc/cGKAONE2MJC3ynC2FsEZRnWqAWXZhTANABWWiDQA4RTitJFXahuavb7dbmfbkfV2RmGmmEqUHPZMGpMx2FsftQApZmTf98tMnLZL+zHqeXqQW7+8Krs59/ytgb4SDAZYysty3m1ioK5gfXwMTO9bB7dydM9Y7bPlcHi4GhuhRdHp9eQttE58KD6in7BeOABQ5UIOCBowZyF8drOhH35dmx1Y1LDjJMc/XfeOON9eYLZd7IWoI+Xxz8+wYcrGzxujc8zyybPlBKBRNCrnXfa6Z9287LfDtkPkhdulRIjVoQV+1Ir5gYJqj5q8dHoyTtK6W7J5Hcm1sJyr8r9Wnsktq8AC6Dlnf5qFKS19gDTQY9fvj2oe0qHkU2hIkTLsT2eJAd3t6NDx1O3tmxml/4szZLGhedXKDXTz0mDOqkNK6faq7E+18jGSKgQhelhbJMNOJo4s0cI3fAJxXrEsQ1KIsv/U3RKVlli+u5aSXQ9dSGzIvdRZUbAsgAT1GS7Co=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
