travis:
  secure:
    BINSTAR_TOKEN: up3InXt9kfj7pFXwaensWKAiTNrha24UfZ90lDessttGyp78T6HPfya3uXcloKm7NIoJ8FqVMuqo4fER+hza/61ZQZpfE6ULIqq+Ov4tverrD3/V0CXCmt4BHVmIHhBTtaQdwMXMUrPG3ogrWRfjsTuhB1oxoIjgX4GJM9RvGN2lF7PWlRXTb7tL+CYN+xg16jVfeoidU3ldl4lmYuz1hyRiPNTm1bVc9ep0bm1EKFvcGCo8V/WpR9uZwfcwgrB+FTHXtWEPswHel4sE8FmpbVLjEwKeMHv9Sj3pZGKlc5/xwmIOW3+kQuCcMGMV44JxiinzcaJPr2wXlHRNsZpfhGlhIIq8vxwegsKT3nC6Wd0HMQ+D3Un8c8csCx3NsehDaWH5VV9QdiQVesGTeyQebz4dphN4OHts8b5ncO3nBZ32JfXCJPpvbDo/ppGAhoAFdAU2khJzKnI9umDzqXIU1purte0DOcZ/TlzW4Jz3z6NaUk/7X/dUxAw/imF7YAIJyyaxHbwFptJ83FAeS1Aj4GT30K6M4FkEiBWekKpGkVutl9sYA3BENYehgqE2CANGv1eNqXxmkewCC8QsIf/HZnqkznnM0haKfAmTGMsqKi6lh/VUoTPcw/yKO/RQBTcLgk8K7BYEmwcAbEj4SVjjT2K4U+47HFLNz3MYFMZQIWk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
